{% set name = "pyformlang" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyformlang-{{ version }}.tar.gz
  sha256: 570b08915220447733753dd0716f537a0d8589aa0f9fa125d7b547872ff1ef6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - networkx
    - numpy
    - pydot

test:
  imports:
    - pyformlang
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Aunsiels/pyformlang
  summary: A python framework for formal grammars
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/Aunsiels/pyformlang

extra:
  recipe-maintainers:
    - johnhany97
