{% set name = "pyformlang" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyformlang-{{ version }}.tar.gz
  sha256: a02c18338c90d4a619a42eef5697874880c7d90f77d0902e4c3abd99db3dce87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - networkx
    - numpy
    - pydot

test:
  imports:
    - pyformlang
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Aunsiels/pyformlang
  summary: A python framework for formal grammars
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/Aunsiels/pyformlang

extra:
  recipe-maintainers:
    - johnhany97
